---
title: "CrimeCapita"
output: html_document
---

```{r}
dataset = read.csv('https://raw.githubusercontent.com/tomasdgus/finalProject2020/master/543GroupDataSet.csv')
```

```{r}
library(questionr)
NumDf = freq(dataset$ViolentCrimePer1000)

NumDf = data.frame(variable=as.numeric(row.names(NumDf)),
                   NumDf,
                   row.names = NULL)
```

```{r}
head(NumDf)
```

```{r}
library(ggplot2)
base = ggplot(data=NumDf, aes(x = variable, y = n))
base + geom_bar(stat = 'identity')
```

```{r}
summary(dataset$ViolentCrimePer1000)
```

```{r}
#standard deviation
sd(dataset$ViolentCrimePer1000, na.rm = T)
```

```{r}
#median absolute deviation
mad(dataset$ViolentCrimePer1000, na.rm = T)
```

```{r}
#asymmetry
library(DescTools)
Skew(dataset$ViolentCrimePer1000, na.rm = T, conf.level = 0.95, ci.type = "bca", R = 3000)
```


```{r}
#shape
Kurt(dataset$ViolentCrimePer1000, na.rm = T, conf.level = 0.95, ci.type = "bca", R=3000)
```

```{r}
base = ggplot(dataset, aes(x = ViolentCrimePer1000))
h1 = base + geom_histogram(binwidth = 2)
h1

d1 = base + stat_density(geom = "line")
d1
```

```{r}
MEAN = summary(dataset$ViolentCrimePer1000)[4]
h1 + geom_vline(xintercept = MEAN)
```

```{r}
theMean = mean(dataset$ViolentCrimePer1000, na.rm = T)
theMedian = median(dataset$ViolentCrimePer1000, na.rm = T)

d1 + geom_vline(xintercept = theMedian, color = 'blue') + geom_vline(xintercept = theMean,
                                                                     color = 'red')
```

```{r}
d1 + geom_vline(aes(xintercept = theMedian,color='median')) +
     geom_vline(aes(xintercept =theMean,color='mean')) +
     scale_color_manual(name = "Measures",
                        values = c(median = "blue", mean = "red"),
                        breaks = c('median','mean'),
                       labels=c("MEDIAN", "MEAN"))
```

```{r}
base = ggplot(dataset, aes(y = ViolentCrimePer1000))
b1 = base + geom_boxplot()
b1 + coord_flip()
```

```{r}
theIQR = IQR(dataset$ViolentCrimePer1000, na.rm = T)
```

```{r}
(upperT = summary(dataset$ViolentCrimePer1000)[[5]] + theIQR*1.5)
```

```{r}
sum(dataset$ViolentCrimePer1000>upperT, na.rm = T)
```

```{r}
theVar=dataset$ViolentCrimePer1000
theIQR = IQR(theVar, na.rm = T)

upperT = summary(theVar)[[5]] + theIQR*1.5
lowerT = summary(theVar)[[2]] - theIQR*1.5

belows = dataset[which(theVar < lowerT),]
normals = dataset[which(theVar >= lowerT & theVar <= upperT),]
aboves = dataset[which(theVar > upperT),]

```

```{r}
base = ggplot(belows, aes(x = ViolentCrimePer1000))
d1b = base + stat_density(geom = 'line') + labs(title = 'belows')

base = ggplot(normals, aes(x = ViolentCrimePer1000))
d1N = base + stat_density(geom = 'line') +labs(title = 'Normals', y = NULL)

base = ggplot(aboves, aes(x = ViolentCrimePer1000))
d1A = base + stat_density(geom = 'line') + labs(title = 'Aboves', y = NULL)
```

```{r}
library(ggpubr)
multid1_a = ggarrange(d1b,d1N,d1A,ncol = 3, nrow = 1)
multid1_a
```

```{r}
#dropping belows because no data falls into that category
multid1_b = ggarrange(d1N,d1A,ncol = 1,nrow = 3)

multid1AN = annotate_figure(multid1_b,
                            top = text_grob("Visualizing Crime Per Capita Distribution",
                                            face = "bold", size = 14),
                            bottom = text_grob("Data source: FBI", 
                                               hjust = 1, x = 1,
                                               face = "italic", 
                                               size = 10),
                            left = "",
                            right = "")

multid1AN
```