```{r}
dataset = read.csv('https://raw.githubusercontent.com/tomasdgus/finalProject2020/master/543GroupDataSet.csv')
```

```{r}
str(dataset)
```
```{r}
dataset$STATE <- as.character(dataset$STATE)
dataset$RegionNumber <- as.numeric(dataset$RegionNumber)
str(dataset)
```

```{r}
library(magrittr)
sort(unique(dataset$STATE))%>%head(20)
```


```{r, eval=TRUE}
USmap="https://raw.githubusercontent.com/tomasdgus/finalProject2020/master/states.json"
```


```{r, eval=TRUE}
library(geojsonio)
PROJmap="+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
USzipMap=topojson_read(USmap,crs=PROJmap,stringsAsFactors = FALSE)
```

```{r, eval=TRUE}
object.size(USzipMap)
```
```{r}
library(rmapshaper)
USzipMap=ms_simplify(USzipMap)
```

```{r, eval=TRUE}
object.size(USzipMap)
```
```{r, eval=TRUE}
library(ggplot2)
ggplot(data=USzipMap) + geom_sf()
```
```{r}
names(USzipMap)
```

```{r}
str(USzipMap$STATE_NAME)
```
```{r}
layerUSMap=merge(USzipMap,dataset, 
                   by.x='STATE_NAME', 
                   by.y='STATE',
                   all.x=F) # if no coincidence don't keep shape.
```

```{r, eval=TRUE,warning=FALSE}

# This will make just a border of the state
baseMap <- ms_dissolve(USzipMap)
```

This is the base map, which may help us show the missing shapes.
```{r, eval=TRUE}
ggplot(baseMap) + geom_sf()
```

```{r, eval=TRUE,warning=FALSE,message=FALSE,results='hide'}
library(RColorBrewer)
library(tmap)
```

2. Decide the amount of groups:

```{r, eval=TRUE}
numberOfClasses = 5
```

3. Decide colors for each group of shapes (I chose a palette from [here](http://colorbrewer2.org/)):
```{r, eval=TRUE}
colorForScale='BuPu' # color scale
RegionColor = 'Pastel1'
```


```{r, eval=TRUE}
layerUSMap1 = layerUSMap

layerUSMap2 = layerUSMap
layerUSMap2$cut=cut_number(layerUSMap$Confidence,5,
                            ordered_result=T,
                            dig.lab=5)
```
```{r}
baseLayer1 = ggplot(data=baseMap) + geom_sf()
layer1 = baseLayer1 +geom_sf(data = layerUSMap1, aes(fill=as.factor(RegionNumber)),show.legend = T)+
    scale_fill_brewer(palette = RegionColor,name="Regions")
layer1
```


```{r}
pacificx = c(-110,-125)
pacificy = c(31,50)
intermountainx =c(-115,-94)
intermountainy = c(27,50)
midwestx = c(-104,-81)
midwesty = c(33,50)
```

```{r}

baseLayer2=ggplot(data = baseMap) +geom_sf() 
layer2 = baseLayer2 + geom_sf(data = layerUSMap2, aes(fill=cut),show.legend = T) +
                 scale_fill_brewer(palette = colorForScale,
                                   name = "Confidence")+theme_classic()
layer2 = layer2 + theme(axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank())
layer2 
```
```{r}
pacific2 = layer2 + coord_sf(xlim = pacificx ,ylim=pacificy)
pacific2
```

